# Generated by Django 4.2.10 on 2024-02-28 10:21

from django.db import migrations, models
import maintenanceShop.models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenanceShop', '0002_rating_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(default=1, upload_to=maintenanceShop.models.image_upload),
            preserve_default=False,
        ),
    ]
