# Generated by Django 4.2.10 on 2024-03-17 16:39

import car.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=366)),
                ('city', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('doors', models.IntegerField()),
                ('aircondition', models.CharField(max_length=255)),
                ('transmition', models.CharField(choices=[('Gear', 'Gear'), ('Automatic', 'Automatic')], max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField(default=2024)),
                ('image', models.ImageField(upload_to=car.models.image_upload)),
                ('color', models.CharField(max_length=255)),
                ('millage', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apoinment', models.DateTimeField()),
                ('client_full_name', models.CharField(max_length=255)),
                ('client_mobile_phone', models.IntegerField(default='+966')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('car_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_buy', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_buy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
